### ISSUE TITLE
Make a plan to have maintainers

### ISSUE THREAD

**Issue by AD7six** [cakephp/datasources#104]
I went through the existing tickets and pull requests for this repo this morning, and sadly community-supported has effectively meant "abandoned". Of the remaining open PRs 4 are **2 years old**, and have had no or almost no feedback - issues are no better.

I think the main problem is that while the core members aren't responsible for the code in this repo, they are the only ones who can close tickets and merge pull requests; yet since we aren't really responsible it's not on our radar to check. It would be beyond awesome to have anyone looking at this repo on a regular ish basis (anything better than once a year would be a massive improvement), and by anyone I mean not me/us.

Ideally what I'd like is for each datasource to have someone responsible with appropriate permissions. It may be too little too late but I propose that anyone contributing a datasource or patch going forwards should by default be asked if they would like to maintain it (it's absolutely fine to say no), I would much rather see a high turnover of maintainers (even though that seems highly unlikely to occur) than code sitting for years unmodified.

**Comment by chinpei215** [comment]
Closing, as I decided to maintain this repository.
