### ISSUE TITLE
ArraySource + Paginator

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/datasources#95]
This is not a real issue, this is rather a question. The plugin - and in particular the ArraySource datasource, supports the sorting provided by the Paginator component?

Using the Paginator component with ArraySource, I see that the paging works correctly, but not the sort (does not work nor the default sort, nor the sort specified by the user clicking on a sort link).

**Comment by 512banque** [comment]
Fixed here:
https://github.com/cakephp/datasources/pull/113

**Comment by mirko-pagliai** [comment]
Nice!

**Comment by jadb** [comment]
Closing this as there is a [PR](/cakephp/datasources/pull/113) for it.
